language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script: python -m coverage run manage.py test --omit='manage.py'
# report coverage
after_success: codecov
